#Requires -Version 5.1
param(
  [string]$OutputName = "Cloudsave",
  [Parameter(Mandatory = $true)]
  [string]$Version
)

$ErrorActionPreference = "Stop"

$ScriptRoot  = Split-Path -Parent $MyInvocation.MyCommand.Path
$AgentScript = Join-Path $ScriptRoot "restore_agent.py"
$VenvDir     = Join-Path $ScriptRoot ".venv"
$PythonExe   = Join-Path $VenvDir "Scripts\python.exe"
$DistDir     = Join-Path $ScriptRoot "dist"
$VersionFile = Join-Path $ScriptRoot "agent_version.py"

if ($Version -notmatch '^\d+\.\d+\.\d+$') {
    throw "Version must use strict x.y.z format (for example, 1.2.3)."
}

# Build identity is source code bundled by PyInstaller, never an environment override.
$escapedVersion = $Version.Replace('"', '\"')
Set-Content $VersionFile -Value "# Generated by build-exe.ps1.`nAGENT_VERSION = `"$escapedVersion`"" -Encoding ASCII

function Step([string]$msg) { Write-Host "`n==> $msg" -ForegroundColor Cyan }

# 1. Find system Python
Step "Finding Python"
$pyCmd = Get-Command python -ErrorAction SilentlyContinue
if (-not $pyCmd) { $pyCmd = Get-Command python3 -ErrorAction SilentlyContinue }
if (-not $pyCmd) { throw "Python not found. Install Python 3.10+ from https://python.org" }
Write-Host "  Using: $(& $pyCmd.Source --version) at $($pyCmd.Source)"

# 2. Create venv if missing
Step "Setting up virtual environment"
if (-not (Test-Path $PythonExe)) {
    Write-Host "  Creating .venv ..."
    & $pyCmd.Source -m venv $VenvDir
}
Write-Host "  .venv OK"

# 3. Install deps + PyInstaller (use python -m pip to avoid permission issue)
Step "Installing dependencies"
& $PythonExe -m pip install --quiet --upgrade pip 2>$null
if ($LASTEXITCODE -ne 0) { throw "Could not upgrade pip (exit code $LASTEXITCODE)." }
& $PythonExe -m pip install --quiet -r (Join-Path $ScriptRoot "requirements.txt")
if ($LASTEXITCODE -ne 0) { throw "Could not install dependencies (exit code $LASTEXITCODE)." }
Write-Host "  Done"

# 4. Build
Step "Building exe with PyInstaller"
$iconPath = Join-Path $ScriptRoot "icon.ico"
$buildArgs = @(
    "-m", "PyInstaller"
    $AgentScript
    "--onefile"
  "--windowed"
    "--name",     $OutputName
    "--distpath", $DistDir
    "--workpath", (Join-Path $ScriptRoot "build\_work")
    "--specpath", (Join-Path $ScriptRoot "build")
    "--clean"
    "--noconfirm"
)
if (Test-Path $iconPath) {
    $iconAbsPath = (Resolve-Path $iconPath).Path
    Write-Host "  Using icon: $iconAbsPath"
    $buildArgs += "--icon"
    $buildArgs += $iconAbsPath
}
& $PythonExe @buildArgs
if ($LASTEXITCODE -ne 0) {
    throw "PyInstaller failed (exit code $LASTEXITCODE). Close Cloudsave.exe if it is running, then build again."
}

# 5. Verify
$exePath = Join-Path $DistDir "$OutputName.exe"
if (-not (Test-Path $exePath)) { throw "Build failed - exe not found: $exePath" }

# 6. README
$guide = @"
=== CloudSave Restore Agent ===
No Python required on target machine.

SETUP:
  1. Copy this folder to target machine (e.g. C:\CloudSaveAgent\)
  2. The backend API is https://api.luugame.fun
  3. Run $OutputName.exe once - a desktop window will show DEVICE NAME and a masked API KEY
  4. Finish the browser login/link flow
  5. After successful login, the app auto-hides to tray and shows toast notifications on sync success

RUN ON STARTUP (no extra software):
  Right-click exe > Create shortcut
  Win+R > shell:startup > move shortcut there

LOGS:
  %LOCALAPPDATA%\CloudSave\logs\agent.log
"@
Set-Content (Join-Path $DistDir "README.txt") -Value $guide -Encoding ASCII

$hash = (Get-FileHash -LiteralPath $exePath -Algorithm SHA256).Hash.ToLowerInvariant()
$length = (Get-Item -LiteralPath $exePath).Length
$manifest = [ordered]@{
    version = $Version
    filename = "$OutputName.exe"
    size = $length
    sha256 = $hash
}
$manifest | ConvertTo-Json | Set-Content (Join-Path $DistDir "$OutputName.manifest.json") -Encoding ASCII

$sizeMB = [math]::Round((Get-Item $exePath).Length / 1MB, 1)
Write-Host ""
Write-Host "BUILD SUCCESSFUL" -ForegroundColor Green
Write-Host "  exe  : $exePath  ($sizeMB MB)"
Write-Host "  sha256: $hash"
Write-Host "  manifest: $(Join-Path $DistDir "$OutputName.manifest.json")"
Write-Host "  dist : $DistDir"
